In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2908, 2993, 6441, 4760],
 [2908, 2993, 6441, 9543],
 [2908, 8183, 6441, 6953],
 [9388, 2012, 2473, 1212, 213],
 [9388, 2012, 2473, 1212, 1848],
 [3467, 2908, 9155, 6441, 8896],
 [1626, 628, 7207, 1212]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2908 2993 6441 4760]
 [   0    0    0    0 2908 2993 6441 9543]
 [   0    0    0    0 2908 8183 6441 6953]
 [   0    0    0 9388 2012 2473 1212  213]
 [   0    0    0 9388 2012 2473 1212 1848]
 [   0    0    0 3467 2908 9155 6441 8896]
 [   0    0    0    0 1626  628 7207 1212]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\PradeepchandraReddyS\Desktop\AI Course\section_13\annproject\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step


array([[[-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03788773, -0.0485562 , -0.03260478, -0.03324791,
         -0.00842371, -0.04469362,  0.01062621,  0.02921693,
          0.01294292, -0.03526573],
        [ 0.04780856, -0.01281248, -0.04330444,  0.00289255,
         -0.01502992, -0.01288401,  0.0311822 ,  0.01929459,
          0.01401316, -0.01683881],
        [-0.0469397 ,  0.01735631, -0.02237356,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 2908, 2993, 6441, 4760], dtype=int32)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03703264, -0.0379192 ,  0.02211187,  0.02276609,
         -0.018442  ,  0.00208332, -0.04748489,  0.00611428,
          0.04820851, -0.04556603],
        [-0.03788773, -0.0485562 , -0.03260478, -0.03324791,
         -0.00842371, -0.04469362,  0.01062621,  0.02921693,
          0.01294292, -0.03526573],
        [ 0.04780856, -0.01281248, -0.04330444,  0.00289255,
         -0.01502992, -0.01288401,  0.0311822 ,  0.01929459,
          0.01401316, -0.01683881],
        [-0.0469397 ,  0.01735631, -0.02237356,  0.0